# http://flask.pocoo.org/docs/config/
database: "sqlite:////var/lib/ipop-stat/ipop-stat.db" # in-memory db
new_database: False
flask:
    debug: true
    testing: true
# http://docs.python.org/2/library/logging.config.html#logging-config-dictschema
logging:
    version: 1
    root:
        level: DEBUG
    handlers:
        console:
            class: logging.StreamHandler
            stream: ext://sys.stdout
            formatter: default
    formatters:
        default:
            format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
ratelimit:
    burst: 10 # allow a burst "pool"
    uuid: 60 # seconds
    ipv4: 60 # seconds
    ipv6: 60 # seconds
